- name: "Proxy" # 手动选择代理节点
  type: select
  proxies:
    - "Auto"
    - "DIRECT"
    - ".*"

- name: "Auto" # 通过指定的 URL 测试并自动选择延迟最低的节点
  type: url-test
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
  proxies:
    - ".*"

- name: "Load-Balance" # 负载均衡
  type: load-balance
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
  proxies:
    - ".*"

- name: "Apple" # Apple 服务代理
  type: select
  proxies:
    - "DIRECT"
    - "Proxy"
    - ".*"

- name: "GlobalMedia" # 国际流媒体服务
  type: select
  proxies:
    - "Proxy"
    - "DIRECT"
    - ".*"

- name: "HKMTMedia" # 大陆流媒体面向港澳台限定服务
  type: select
  proxies:
    - "Proxy"
    - "DIRECT"
    - ".*"

- name: "Speedtest" # 测速专用
  type: select
  proxies:
    - "DIRECT"
    - ".*"

- name: "Hijacking" # 运营商及声名狼藉网站劫持
  type: select
  proxies:
    - "REJECT"
    - "DIRECT"